[build]
  publish = "."

[[redirects]]
  from = "/index"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/brand"
  to = "/brand.html"
  status = 200

[[redirects]]
  from = "/products"
  to = "/products.html"
  status = 200

[[redirects]]
  from = "/support"
  to = "/support.html"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/contact.html"
  status = 200

[[redirects]]
  from = "/dealer"
  to = "/dealer.html"
  status = 200

[[redirects]]
  from = "/checkout"
  to = "/checkout.html"
  status = 200
